/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package simple.banking

import java.util.Scanner


class Session {
    fun op(i: Int) {
        val reader = Scanner(System.`in`)
        when(i) {
            0 -> print("Exiting program...")
            else -> {
                when (i) {
                    1 -> println("Creating a new account...")
                    2 -> println("Logging into existing account...")
                    else -> print("Incorrect input. Choose again: ")
                }
                op(reader.nextInt())
            }
        }
    }

    fun run(): Unit {
        val reader = Scanner(System.`in`)
        op(reader.nextInt())
    }
}

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    val session = Session()
    session.run()
}
